name:                haskellrs
version:             0.1.0.0
github:              "githubuser/haskellrs"
license:             BSD3
author:              "Antony Vennard"
maintainer:          "antony@vennard.ch"
copyright:           "2020 Antony Vennard"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/haskellrs#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  exposed-modules: FFI
  other-extensions: ForeignFunctionInterface
  extra-libraries:     rustlib, pthread

executables:
  haskellrs-exe:
    main:                Main.hs
    source-dirs:         app
    extra-libraries:     rustlib, pthread
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskellrs

